services:
    - docker
language: shell
env:
  global:
    - ROCKER_VERSION=1.3.0
    - SKIP_REMOVE=true
  matrix:
    - IMAGE=alpine
    - IMAGE=centos
    - IMAGE=debian
    - IMAGE=fedora
    - IMAGE=ubuntu
    - IMAGE=archlinux SOURCE_IMAGE=pritunl/archlinux
addons:
  apt:
    packages:
    - parallel
    - jq
before_script:
  - curl -L https://github.com/grammarly/rocker/releases/download/${ROCKER_VERSION}/rocker_linux_amd64.tar.gz | sudo tar -C /usr/bin -xzf -
script:
  - ./scripts/build.sh
