language: shell

arch:
  - amd64
  - arm64

services:
    - docker

env:
  global:
    - SKIP_REMOVE=true
  matrix:
    - IMAGE=alpine
    - IMAGE=centos
    - IMAGE=debian
    - IMAGE=fedora
    - IMAGE=ubuntu
    - IMAGE=archlinux SOURCE_IMAGE=pritunl/archlinux

addons:
  apt:
    packages:
    - parallel
    - jq

script:
  - ./travis-helpers/build.sh
